on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: actions/setup-node@master
    - name: Setup and Test
      run: |
        npm install --upgrade yarn
        yarn install
        yarn gulp build
        yarn mocha
        yarn tsc
        bash test/auto.sh
